# =============================================================================
# Helm Chart 메타데이터 (Chart.yaml)
# =============================================================================
# Chart.yaml은 Helm 차트의 메타데이터를 정의하는 필수 파일입니다.
# 차트 이름, 버전, 설명 등의 정보를 포함합니다.
#
# Helm 차트 구조:
#   sample-app/
#   ├── Chart.yaml      # 차트 메타데이터 (현재 파일)
#   ├── values.yaml     # 기본 설정값
#   └── templates/      # Kubernetes 매니페스트 템플릿
#       ├── _helpers.tpl
#       ├── deployment.yaml
#       └── service.yaml
# =============================================================================

# -----------------------------------------------------------------------------
# API 버전
# -----------------------------------------------------------------------------
# apiVersion: v2는 Helm 3용 차트를 의미
# Helm 2는 apiVersion: v1을 사용 (더 이상 지원되지 않음)
apiVersion: v2

# -----------------------------------------------------------------------------
# 차트 이름
# -----------------------------------------------------------------------------
# 차트의 고유 식별자
# helm install [릴리스명] [차트경로] 명령에서 사용
# 예: helm install sample-app ./helm-charts/sample-app
name: sample-app

# -----------------------------------------------------------------------------
# 차트 설명
# -----------------------------------------------------------------------------
# 차트의 목적과 기능을 설명하는 텍스트
# helm search 결과에 표시됨
description: A Helm chart for sample nginx application

# -----------------------------------------------------------------------------
# 차트 타입
# -----------------------------------------------------------------------------
# application: 배포 가능한 애플리케이션 차트 (기본값)
# library: 다른 차트에서 재사용하는 헬퍼/템플릿 모음 (직접 배포 불가)
type: application

# -----------------------------------------------------------------------------
# 차트 버전 (Chart Version)
# -----------------------------------------------------------------------------
# 차트 자체의 버전 (SemVer 형식 권장)
# 차트 구조, 템플릿, 기본값 등이 변경될 때 업데이트
# helm upgrade 시 이 버전을 기준으로 변경사항 추적
version: 0.1.0

# -----------------------------------------------------------------------------
# 애플리케이션 버전 (App Version)
# -----------------------------------------------------------------------------
# 차트가 배포하는 애플리케이션의 버전
# 차트 버전과 독립적으로 관리
# 예: nginx 1.25.0을 배포하면 appVersion: "1.25.0"
# 정보 제공 목적이며, 실제 이미지 태그는 values.yaml에서 설정
appVersion: "1.0.0"
