# =============================================================================
# ArgoCD Application 리소스
# =============================================================================
# ArgoCD Application은 GitOps 배포의 핵심 리소스입니다.
# Git 저장소의 특정 경로를 감시하고, 변경사항을 자동으로 클러스터에 동기화합니다.
#
# 동작 방식:
#   1. ArgoCD가 주기적으로 Git 저장소를 폴링 (기본 3분)
#   2. 저장소의 매니페스트와 클러스터 상태를 비교
#   3. 차이가 있으면 자동으로 동기화 (auto-sync 활성화 시)
#
# 이 Application은 helm-charts/sample-app 경로의 Helm 차트를
# sample 네임스페이스에 배포합니다.
# =============================================================================

# ArgoCD CRD(Custom Resource Definition) API 버전
apiVersion: argoproj.io/v1alpha1

# 리소스 종류: Application
kind: Application

metadata:
  # Application 이름: ArgoCD UI에서 이 이름으로 표시됨
  name: sample-app

  # Application 리소스는 반드시 argocd 네임스페이스에 생성해야 함
  # ArgoCD controller가 이 네임스페이스의 Application만 감시
  namespace: argocd

spec:
  # ---------------------------------------------------------------------------
  # 프로젝트 설정
  # ---------------------------------------------------------------------------
  # ArgoCD 프로젝트: 애플리케이션을 그룹화하고 접근 권한을 관리
  # 'default' 프로젝트는 모든 소스와 대상을 허용하는 기본 프로젝트
  project: default

  # ---------------------------------------------------------------------------
  # 소스 설정 (Source)
  # ---------------------------------------------------------------------------
  # 배포할 매니페스트가 위치한 Git 저장소 정보
  source:
    # Git 저장소 URL (HTTPS 또는 SSH)
    # Private 저장소의 경우 ArgoCD에 credentials 설정 필요
    repoURL: https://github.com/flex-junehyukhong/crac-infra-local.git

    # 대상 브랜치/태그/커밋
    # HEAD: 기본 브랜치의 최신 커밋
    # 특정 브랜치: "main", "develop"
    # 특정 태그: "v1.0.0"
    # 특정 커밋: "abc1234"
    targetRevision: HEAD

    # 저장소 내 Helm 차트 경로
    # 이 경로에 Chart.yaml이 존재해야 함
    path: helm-charts/sample-app

    # Helm 관련 설정
    helm:
      # 사용할 values 파일 목록
      # 여러 파일 지정 시 나중 파일이 이전 파일을 오버라이드
      valueFiles:
        - values.yaml

  # ---------------------------------------------------------------------------
  # 대상 설정 (Destination)
  # ---------------------------------------------------------------------------
  # 매니페스트를 배포할 Kubernetes 클러스터와 네임스페이스
  destination:
    # 대상 클러스터 API 서버 주소
    # https://kubernetes.default.svc: ArgoCD가 설치된 동일 클러스터
    # 외부 클러스터의 경우 해당 클러스터의 API 서버 주소 입력
    server: https://kubernetes.default.svc

    # 배포 대상 네임스페이스
    # 모든 리소스가 이 네임스페이스에 생성됨
    namespace: sample

  # ---------------------------------------------------------------------------
  # 동기화 정책 (Sync Policy)
  # ---------------------------------------------------------------------------
  syncPolicy:
    # -------------------------------------------------------------------------
    # 자동 동기화 설정
    # -------------------------------------------------------------------------
    # 활성화 시 Git 변경사항이 자동으로 클러스터에 적용됨
    automated:
      # prune: true
      # Git에서 삭제된 리소스를 클러스터에서도 자동 삭제
      # false일 경우 수동으로 삭제해야 함 (안전하지만 리소스 누적 가능)
      prune: true

      # selfHeal: true
      # 클러스터에서 수동으로 변경된 리소스를 Git 상태로 자동 복원
      # kubectl로 직접 수정해도 ArgoCD가 원래 상태로 되돌림
      # 이를 통해 Git을 Single Source of Truth로 유지
      selfHeal: true

    # -------------------------------------------------------------------------
    # 동기화 옵션
    # -------------------------------------------------------------------------
    syncOptions:
      # CreateNamespace=true
      # 대상 네임스페이스가 없으면 자동 생성
      # false일 경우 네임스페이스가 없으면 동기화 실패
      - CreateNamespace=true
